---
title: "Introductory Modelling Resources"
toc: true
format:
    html:
        page-layout: full
---

Infectious disease models can be useful to decision-makers in informing public health policy. Here are some excellent resources to help you learn more about infectious disease models.

## The Bjørnstad modelling series:  
* Bjørnstad, O.N., Shea, K., Krzywinski, M., and Altman, N., 2020. Modeling infectious epidemics. Nature Methods, 17(5), pp.455-456. <https://doi.org/10.1038/s41592-020-0822-z>
* Bjørnstad, O.N., Shea, K., Krzywinski, M. and Altman, N., 2020. The SEIRS model for infectious disease dynamics. Nature Methods, 17(6), pp.557-558. <https://doi.org/10.1038/s41592-020-0856-2> 
* Shea, K., Bjørnstad, O.N., Krzywinski, M. and Altman, N., 2020. Uncertainty and the management of epidemics. Nature Methods, 17(9), pp.867-868. <https://doi.org/10.1038/s41592-020-0943-4> 

This set of free articles on Nature Methods goes through some basic infectious disease models, how to interpret them and how to account for uncertainty in models. Each article is two pages long, making them convenient for quickly learning how to interpret and understand infectious disease models. 

## Vynnycky, E. and White, R., 2010. An Introduction to Infectious Disease Modelling. Oxford University Press. 

This is an excellent textbook on how mathematical equations can be used to build infectious disease models. Unlike other textbooks on infectious disease models, you do not need a strong mathematics background to understand the contents of the book. This is a great textbook to read for a comprehensive understanding of different parts of infectious disease models. 

For more about the book, see [here](https://anintroductiontoinfectiousdiseasemodelling.com/). 

If you'd like to purchase the book, it is available on [Amazon](https://www.amazon.com/Introduction-Infectious-Disease-Modelling/dp/0198565763/ref=sr_1_1?crid=58M4R6Q5ZZAJ&keywords=An+Introduction+to+Infectious+Disease+Modelling)

## Johnson, L., 2016. Agent-Based Model Basics: A Guidebook & Checklist for Policy Researchers. Westphalia Press. 

Although not specific to infectious diseases, this short book outlines what agent-based models (models involving computer simulations) are and how they are used in policymaking. This is a great book for those who are interested in learning more about this emerging area of infectious disease modelling. 

If you'd like to pucahse the book, it is available on [Amazon](https://www.amazon.com/Agent-Based-Model-Basics-Guidebook-Researchers-ebook/dp/B01FKVDMLM/ref=sr_1_1?crid=HCPL128PIII1&keywords=Agent-Based+Model+Basics%3A+A+Guidebook+%26+Checklist+for+Policy+Researchers) 

## Campbell, P., Geard, N., Glass, K., McBryde, E., McCaw, J., McVernon, J., Moss, R., Ross, J., and Wood, J., 2016. A User’s Guide to Infectious Disease Modelling. University of Melbourne.

This guide is intended for policymakers and public health practitioners who want to learn how to interpret the results of infectious disease modelling studies. It not only goes through the basics of infectious disease models and economic evaluation, but it also gives a set of guidelines for assessing whether an infectious disease model answers your policy questions.  

The guide is available online [here](http://prism.edu.au/wp-content/uploads/2016/09/PRISM_Modelling-guidelines-web.pdf)

## Kucharski, A., 2020. The Rules of Contagion: Why Things Spread - and Why They Stop. Profile Books Ltd. 

This is a comprehensive general interest book that explains how mathematical models can be applied not only to infectious diseases, but also financial panics, memes and much more. Although the book is long, the book does not use much mathematics to explain how mathematical models work and how they can be applied in real-life. This book is great for those that want to know how mathematical models are used in other areas of public policy, not just public health.  

For more information about the book, see Adam Kurchaski's [website](https://kucharski.io/books/) and another description [here](https://profilebooks.com/work/the-rules-of-contagion/). 

If you'd like to purchase the book, it is available on [Amazon](https://www.amazon.com/Rules-Contagion-Things-Spread-They/dp/1541674316)