---
title: "People"
format:
    html:
        anchor-sections: false
---

```{css, echo=FALSE}
@media (max-width: 400px) and (min-height: 600px) {
    .boxes {
        display: block;

        .col {
            width: 100%;
            margin=0 0 5px 0;
        }
    }
}

.personimg img {
    object-fit: contain;
    max-height: 250px;
    min-height: 250px;
}

.boxes {
    justify-content: left;
}

.col {
    display: block;
    text-align: center;
}

.col:hover {
    background-color: #dcdcdc;
}

h3 {
    text-align: center;
    min-height: 1.5em;
    margin-top: 0.5rem !important;
}
```

```{r setup, include=FALSE}
#| echo: false
#| warning: false
#| message: false
knitr::opts_chunk$set(echo = FALSE)
source("load_data.R")
library(tools)
```

## Chief Investigators and Executive
```{r, results='asis'}
flist <- list.files("images/staff")
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "ci") {
        fileext <- flist[grepl(staff_member$id, flist)] %>% file_ext()
        condensr::generate_markdown_for_member(staff_member, extension = fileext)
    }
}
cat("::::")
```

## SPARK Fellows

```{r, results='asis'}
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "fellow") {
       fileext <- flist[grepl(staff_member$id, flist)] %>% file_ext()
        condensr::generate_markdown_for_member(staff_member, extension = fileext)
    }
}
cat("::::")
```

## Research and Support Staff

```{r, results='asis'}
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "researcher" | staff_member$staff_type == "research-support") {
        fileext <- flist[grepl(staff_member$id, flist)] %>% file_ext()
        condensr::generate_markdown_for_member(staff_member, extension = fileext)
    }
}
cat("::::")
```

## Students

```{r, results='asis'}
cat(":::: boxes \n")
for (staff_member in staff_list) {
    if (staff_member$staff_type == "student") {
        fileext <- flist[grepl(staff_member$id, flist)] %>% file_ext()
        condensr::generate_markdown_for_member(staff_member, extension = fileext)
    }
}
cat("::::")
```