---
title: "SPECTRUM-SPARK EMCR Meeting - 8 May 2023"
description: "EMCR meetings are back for 2023"
author: "Michael Lydeamore"
date: 2023-05-01
categories:
    - EMCR Network
    - Networking
---

On May 8, the SPECTRUM & SPARK EMCR Network will meet for the first time in 2023. Anyone who identifies themselves as an EMCR in the network is welcome to attend. If you are not on the list and want to be, please email <spectrum-spark@unimelb.edu.au>.

## The sessions

This year, we are going for a more structured approach to the meetings, although the meetings will remain virtual. We will be alternating between two formats:

1. A career skills and/or networking session and WIP talk from a network member
2. A training session

This month, we'll start with some icebreakers so we can all remember who we all are, and welcome anyone new into the network. Then, Isobell Abell will give a WIP presentation on some of her recent work.

## Feedback

We'd love to hear what _you_ want out of these sessions. If you have any ideas, or would like to sign up for a WIP talk, or to run a training session, please let the EMCR Chair (Michael Lydeamore) know by emailing in <spectrum-spark@unimelb.edu.au>.
